# action.yml
name: 'Custom Action'
description: 'List clusters of DB system'
inputs:
  runner_ip:  # id of input
    description: 'IP address of the GitHub Runner'
    required: true
    default: '0.0.0.0'
outputs:
  clusters_list: # id of output
    description: 'List of clusters'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.runner_ip }}