# Give a name to the workflow
name: Demo 2nd Workflow

# To automatically trigger a workflow, use on to define which events can cause the workflow to run.
on: [workflow_dispatch]

jobs:

  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Development Environment
        run: echo "Deploy the apps to Dev"

  qa:
    needs: dev
    runs-on: ubuntu-latest
    steps:
      - name: 2nd job
        run: |
            echo "This is 2nd job"
            curl https://www.google.com/
            sleep 30

  prod:
    needs: [dev, qa]
    runs-on: ubuntu-latest
    steps:
      - name: 3rd job
        run: echo "This is 3rd job"