# Give a name to the workflow
name: Mongo Backup

# To automatically trigger a workflow, use on to define which events can cause the workflow to run.
on: [push]

jobs:
  mongo_connection:
    runs-on: macos-latest
    steps:
      - name: MongoDB Connection
        run: |
          echo "Connecting to MongoDB Atlas......"
          brew install mongodb-atlas
          atlas --version

          echo -e "\n\n============Configuration Setup===============\n\n"
          atlas config set public_api_key eapwhggt
          atlas config set private_api_key bf054837-de09-42ed-8b98-6b4fea68eb8a
          atlas config set project_id 62f3427084a04c48f05f8a7e
          atlas config set org_id 62f342087fa66d7a256e53b5
          ifconfig -l | xargs -n1 ipconfig getifaddr

          echo -e "\n\n============Cluster List===============\n\n"
          atlas clusters list

          echo -e "\n\n============Backup Snapshots List===============\n\n"
          atlas backups snapshots list ecam

          echo -e "\n\n============Backup Snapshots Creation===============\n\n"
          atlas backups snapshots create ecam --desc "snapshot created by github workflow"
