# Give a name to the workflow
name: Mongo Backup

# To automatically trigger a workflow, use on to define which events can cause the workflow to run.
on: [push]

jobs:
  mongo_connection:
    runs-on: macos-latest
    steps:
      - name: MongoDB Connection in progress......
        uses: ./.github/actions/mongo_backup.sh
  connection_completed:
    needs: mongo_connection
    runs-on: ubuntu-latest
    steps:
      - name: MongoDB Connection Status
        run: echo "MongoDB Connection is successful!"